version: "3.2"

services:
  rabbit_mq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbit_mq'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
